name: Run Selenium tests on push

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: 19

    - name: Install ChromeDriver
      run: |
        LATEST=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Start Selenium server
      run: |
        wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
        java -jar selenium-server-standalone-3.141.59.jar &

    - name: Run Selenium tests
      run: |
        mvn test -Dtest=SeleniumTest -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
